
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - UITests
 - Pods
 - XCFrameworks
 - Frameworks
 - Tuist/Dependencies/SwiftPackageManager
disabled_rules:
  - line_length
  - type_body_length
  - identifier_name
  - trailing_whitespace
opt_in_rules:
  - closure_spacing
  - closure_end_indentation
  - closure_body_length
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_is_empty
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - fallthrough
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - multiline_function_chains
  - multiline_parameters_brackets
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters
  - no_extension_access_modifier
  - operator_usage_whitespace
  - private_action
  - private_outlet
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_type_annotation
  - sorted_first_last
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_opening_braces
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - discouraged_optional_collection
  - trailing_closure
  - legacy_multiple
  - legacy_random
  - indentation_width
force_cast: error          # [NG] as!
force_unwrapping: error    # [NG] value!
indentation: 2
file_length:
 - 2500
 - 3000
large_tuple:
 - 5
 - 6


