# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself

# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  TEST_SIMULATORS = ['iPhone 8','iPhone 13 Pro Max']
  lane :custom_lane do
    run_tests(scheme: "TechCareerGraduationProject-Workspace",
	      clean: false,
	      devices: TEST_SIMULATORS,
              test_without_building: true)
    # add actions here: https://docs.fastlane.tools/actions	
    # add actions here: https://docs.fastlane.tools/actions
  end
end
